services:
 .ravenox-gateway:
    image: ${RAVENOX_IMAGE:.ravenox:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      RAVENOX_GATEWAY_TOKEN: ${RAVENOX_GATEWAY_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${RAVENOX_CONFIG_DIR}:/home/node/.ravenox
      - ${RAVENOX_WORKSPACE_DIR}:/home/node/.ravenox/workspace
    ports:
      - "3008:18789"
      - "3009:18790"
    init: true
    restart: unless-stopped
    command: [ "node", "dist/index.js", "gateway", "--bind", "${RAVENOX_GATEWAY_BIND:-lan}", "--port", "18789" ]

 .ravenox-cli:
    image: ${RAVENOX_IMAGE:.ravenox:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      RAVENOX_GATEWAY_TOKEN: ${RAVENOX_GATEWAY_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${RAVENOX_CONFIG_DIR}:/home/node/.ravenox
      - ${RAVENOX_WORKSPACE_DIR}:/home/node/.ravenox/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: [ "node", "dist/index.js" ]
