export const browserCoreExamples = [
  "ravenox browser status",
  "ravenox browser start",
  "ravenox browser stop",
  "ravenox browser tabs",
  "ravenox browser open https://example.com",
  "ravenox browser focus abcd1234",
  "ravenox browser close abcd1234",
  "ravenox browser screenshot",
  "ravenox browser screenshot --full-page",
  "ravenox browser screenshot --ref 12",
  "ravenox browser snapshot",
  "ravenox browser snapshot --format aria --limit 200",
  "ravenox browser snapshot --efficient",
  "ravenox browser snapshot --labels",
];

export const browserActionExamples = [
  "ravenox browser navigate https://example.com",
  "ravenox browser resize 1280 720",
  "ravenox browser click 12 --double",
  "ravenox browser type 23 "hello" --submit',
  "ravenox browser press Enter",
  "ravenox browser hover 44",
  "ravenox browser drag 10 11",
  "ravenox browser select 9 OptionA OptionB",
  "ravenox browser upload /tmp()/uploads/file.pdf",
  "ravenox browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ravenox browser dialog --accept",
  "ravenox browser wait --text "Done"',
  "ravenox browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ravenox browser console --level error",
  "ravenox browser pdf",
];
